# https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix
# => run: docker version để biết enginer version bao nhiêu
# version: "3.9"
services:
  nginx:
    container_name: my-nginx
    depends_on:
      - backend
    restart: always # because it is routing traffic to our entire app
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80

    volumes:
      # - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    container_name: my-db
    command: --init-file /data/application/init.sql
    volumes:
      - ./initDB.sql:/data/application/init.sql
    environment:
      # - MYSQL_USER=root => root user created automatically
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=daituparishchurch
    expose:
      - "3306"

  backend:
    depends_on:
      - mysqldb
    restart: unless-stopped
    container_name: my-backend
    build:
      context: ./BE-web-giao-xu
    environment:
      - HOST=mysqldb
    links:
      - mysqldb
    expose:
      - "8000"
  # docker compose -p hoidanit up -d
